#!/bin/bash

user_display_name="$(git config user.name)"

function error_out {
    2>&1 echo "Please set your user display name properly (use your proper name please):"
    2>&1 echo ""
    2>&1 echo "  git config user.name \"John Doe\"           # <= for this repo only"
    2>&1 echo "  git config --global user.name \"John Doe\"  # <= or set a machine default"
    2>&1 echo ""
    exit 1
}

function print_error_msg {
    2>&1 echo "[ERROR] $@"
    2>&1 echo "Your current value: \`$user_display_name\`"
    2>&1 echo ""
    error_out
}

# prevent empty user display name
if [[ "${user_display_name}" =~ ^\ *$ ]]; then
    print_error_msg "User display name must be set."
fi

# prevent punctuation chars
if [[ "${user_display_name}" =~ ^[[:punct:]] ]]; then
    print_error_msg "User display name cannot begin with a punctuation char ([!\"#$%&'()*+,-./:;<=>?@[\]^_\`{|}~])."
fi
if [[ "${user_display_name}" =~ [[:punct:]]$ ]]; then
    print_error_msg "User display name cannot end with a punctuation char ([!\"#$%&'()*+,-./:;<=>?@[\]^_\`{|}~])."
fi

# prevent user display name being the same as CEC id
user_email="$(git config user.email)"
user_cec_id="${user_email%%@*}"
if [ "${user_display_name}" = "${user_cec_id}" ]; then
    error_out
fi
