#!/bin/bash

function error_out {
    2>&1 echo "Please set your user display name properly (use your proper name please):"
    2>&1 echo ""
    2>&1 echo "  git config user.name \"John Doe\"           # <= for this repo only"
    2>&1 echo "  git config --global user.name \"John Doe\"  # <= or set a machine default"
    2>&1 echo ""
    exit 1
}

# prevent empty user display name
user_display_name="$(git config user.name)"
if [[ "${user_display_name}" =~ ^\ *$ ]]; then
    error_out
fi

# prevent user display name being the same as CEC id
user_email="$(git config user.email)"
user_cec_id="${user_email%%@*}"
if [ "${user_display_name}" = "${user_cec_id}" ]; then
    error_out
fi
