#!/bin/bash

function has_added_new_js_files {
    git diff --cached --name-status | grep "^A" | grep "app/" | grep -q ".js$"
    return $?
}

# early-out if no new js files added
if ! has_added_new_js_files; then
    exit 0
fi

2>&1 echo "[ERROR] Adding new '*.js' files under './app' is no longer allowed."
2>&1 echo ""
2>&1 echo "Please convert your logic to TypeScript and save as '*.ts'."
exit 1
