module.exports = {
  common: [
    { group: 'usage', url: 'minute/meeting', type: 'column', title: 'TOTAL DATA MEETING MINUTES' },
    { group: 'usage', url: 'minute/audio', type: 'column', title: 'AUDIO MINUTES BY CALL TYPE' },
    { group: 'usage', url: 'minute/video', type: 'line', title: 'VIDEO MEETING MINUTES' },
    { group: 'usage', url: 'minute/audio/session-type', type: 'column', title: 'AUDIO MINUTES BY SESSION TYPE' },
    { group: 'usage', url: 'minute/audio/pstn', type: 'column', title: 'TOTAL AUDIO PSTN MINUTES' },
    { group: 'usage', url: 'minute/audio/cca', type: 'column', title: 'TOTAL AUDIO CCA MINUTES' },
    { group: 'peakPorts', url: 'peakport/meeting', type: 'column', title: 'PEAK DATA PORTS' },
    { group: 'peakPorts', url: 'peakport/audio', type: 'line', title: 'PEAK AUDIO PORTS' },
    { group: 'peakPorts', url: 'peakport/video', type: 'column', title: 'PEAK VIDEO PORTS' },
    { group: 'participants', url: 'participants/host-method', type: 'column', title: 'HOST SCHEDULING METHOD' },
    { group: 'participants', url: 'participants/attend-method', type: 'column', title: 'ATTENDANCE METHOD' },
    { group: 'participants', url: 'participants/hosts', type: 'columns', title: 'ACTIVE WEBEX HOSTS' },
    { group: 'participants', url: 'participants/attendees', type: 'column', title: 'TOTAL ATTENDEES' },
    { group: 'participants', url: 'quantity/meeting/size', type: 'line', title: 'AVERAGE MEETING SIZE BY NUMBER OF PARTICIPANTS' },
  ],
  color: {
    SC3: '#43A942',
    TRS: '#F5A623',
    ONS: '#FDEBCD',
    RAS: '#E9691E',
    AUO: '#049FD9',
    PRO: '#C5E9F7',
    VOIP: '#43A942',
    PSTN: '#F5A623',
    CCA: '#FDEBCD',
    PSTNIN: '#049FD9',
    PSTNOUT: '#C5E9F7',
    CCAIN: 'FDEBCD',
    CCAOUT: '#FDEBCD',
    CALLIN: '#049FD9',
    CALLBACK: '#C5E9F7',
    OTHER: '#AEAEAE',
    'N/A': '#AEAEAE',
    EGRESS: '#049FD9',
    INGRESS: '#8BCA8A',
    AUDIO: '#F5A623',
    ACTIVE: '#049FD9',
    REGISTERED: '#C5E9F7',
    POWER: '#43A942',
    MSN: '#F57944',
    WEBEX: '#D3385E',
    PT_OC_CLIENT: '#FDEBCD',
    UNSPECIFIED: '#2EB64E',
    ANDROID: '#06B9DB',
    SAMETIME: '#A866FF',
    SKYPE: '#FF8AA3',
    YAHOO: '#FF968A',
    OI: '#DD612F',
    BLACKBERRY: '#F5A623',
    NI: '#82E59A',
    SAMSUNG: '#6AD9EE',
    IPHONE: '#CAA3FF',
    MACIE: '#CAA3FF',
    WINMOBILEIE: '#DD612F',
    MACNETSCAPE: '#FF968A',
    MACCHROME: '#A866FF',
    FLASHCHROME: '#06B9DB',
    FLASHIE: '#2EB64E',
    MACSAFARI: '#FDEBCD',
    WINDOWSCHROME: '#D3385E',
    WINDOWSFIREFOX: '#F57944',
    WINDOWSIE: '#43A942',
    MACFIREFOX: '#049FD9',
    IPHONESTANDALONEAPP: '#82E59A',
    ANDROIDSTANDALONEAPP: '#F57944',
    VIDEODEVICESTANDALONEAPP: '#F5A623',
    TANDBERGTELEPRESENCESTANDALONEAPP: '#6AD9EE',
  },
};
