---
  extends:
    - "../.eslintrc.yml"
    - "angular"
  env:
    # We don't want to add "Notification" or "status" as globals
    browser: false
  rules:
    # airbnb-config inherited rules
    array-callback-return: 0
    block-scoped-var: 0
    brace-style: 0
    curly: 0
    default-case: 0
    dot-notation: 0
    guard-for-in: 0
    new-cap: 0
    no-alert: 0
    no-cond-assign: 0
    no-loop-func: 0
    no-param-reassign: 0
    no-restricted-syntax: 0
    no-self-assign: 0
    no-spaced-func: 0
    no-throw-literal: 0
    no-trailing-spaces: 0
    no-useless-concat: 0
    no-useless-escape: 0
    one-var-declaration-per-line: 0
    one-var: 0
    radix: 0
    strict: 0
    wrap-iife: 0
    yoda: 0
    # override eslint-angular-config rules
    angular/angularelement: 0
    angular/controller-as-route: 0
    angular/controller-as-vm: 0
    angular/controller-as: 0
    angular/controller-name: 0
    angular/definedundefined: 0
    angular/empty-controller: 2
    angular/document-service: 0
    angular/di-unused: 2
    angular/json-functions: 0
    angular/module-getter: 0
    angular/no-private-call: 0
    angular/no-service-method: 0
    angular/no-services: 0
    angular/on-watch: 0
    angular/timeout-service: 0
    angular/typecheck-array: 0
    angular/typecheck-function: 0
    angular/window-service: 0
  globals:
    _: true
    $: true
    afterEach: true
    AmCharts: true
    angular: true
    bard: true
    beforeEach: true
    describe: true
    expect: true
    fail: true
    getJSONFixture: true
    inject: true
    installPromiseMatchers: true
    it: true
    jasmine: true
    jstz: true
    moment: true
    phoneUtils: true
    sinon: true
    spyOn: true
    xdescribe: true
    xit: true
