#!/bin/bash

this_pwd="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1090
. "$this_pwd/include/pre-rebase-helpers"

if file_has_changed ".proj-comms/announcement"; then
    print_notice_banner ".proj-comms/announcement"
fi
