#!/bin/bash

this_pwd="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1090
. "$this_pwd/include/pre-rebase-helpers"

if file_has_changed "package.json"; then
    print_notice_banner <<_EOF
'package.json' has changed (see below for diff).

Re-running \`npm install\` is advised.
_EOF
    diff_changed_file "package.json"
fi
