#!/bin/bash

this_pwd="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1090
. "$this_pwd/include/pre-rebase-helpers"

if file_has_changed "yarn.lock"; then
    cat <<_EOF | print_notice_banner
'yarn.lock' has changed (see below for diff).

Re-running \`yarn\` is advised.
_EOF
    diff_changed_file "yarn.lock"
fi
