#!/bin/bash

this_pwd="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
this_file_name="$(basename "${BASH_SOURCE[0]}")"

# invoke the script of the same name, but in the sibling 'pre-rebase' dir, passing 'ORIG_HEAD'
"${this_pwd}/../pre-rebase/${this_file_name}" "ORIG_HEAD"
